module.exports.descriptors = [
    'Beachside',
    'Southern',
    'The Blackstone',
    'Malibu',
    'Rooftop',
    'Paradise Palm',
    'The Royal',
    'Residence',
    'Boulevard',
    'Night',
    'Brooklyn',
    'Royal',
    'Paradise',
    'Ocean',
    'Roadside',
    'Magical',
    'SereneStay',
    'Countryside'
]

module.exports.places = [
    'Inn',
    'Village',
    'Resort',
    'Boracay',
    'Hotel',
    'Paradise',
    'villa',
    'Avenue',
    'Tower',
    'Park Hotel',
    'Motel',
    'Springs',
    'Plaza Hotel',
    'Court Hotel',
    'Boarding House',
    'House',
    'Stay',
    'Cottages',
    ' Grand Del Mar',
    'Grand Hyatt',
    'Ocean Lodge'
]